name: Checks ➜ Tests ➜ Publish

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  checks:
    name: Checks with Linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: nodutilus/project-config/actions/setup-node-latest@main
      - uses: nodutilus/project-config/actions/setup-npm@main
      - uses: nodutilus/project-config/actions/eslint@main
      - uses: nodutilus/project-config/actions/eslintcc@main
      - uses: nodutilus/project-config/actions/ts-check@dev/ts-check

  tests:
    name: Test on ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@main
      - uses: nodutilus/project-config/actions/setup-node-latest@main
      - uses: nodutilus/project-config/actions/setup-npm@main
      - uses: nodutilus/project-config/actions/test@main

  coverage:
    name: Check Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: nodutilus/project-config/actions/setup-node-latest@main
      - uses: nodutilus/project-config/actions/setup-npm@main
      - uses: nodutilus/project-config/actions/c8@main

  build-and-publish:
    name: Build & Publish
    needs: [checks, tests, coverage]
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: nodutilus/project-config/actions/setup-node-latest@main
      - uses: nodutilus/project-config/actions/setup-npm@main
      - uses: nodutilus/project-config/actions/npm-publish@main
        with:
          token: ${{ secrets.NPM_TOKEN }}
